name: "publish"

on:
  push:
    branches:
      - release

jobs:
  publish-rust:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Package
        shell: bash
        run: |
          mkdir -p release
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            cp target/${{ matrix.target }}/release/*.exe release/
          else
            cp target/${{ matrix.target }}/release/* release/
          fi

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*
          tag_name: v${{ github.run_number }}
          name: Release ${{ github.run_number }}
          body: |
            Automated release for version ${{ github.run_number }}.
            See the assets to download this version.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}